language: python
cache: pip
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install pipenv
# command to install dependencies
install:
  # - pipenv install --dev
  - pip install .
# command to run tests
script:
  - pytest
