[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "blue_chip"
author = "Gabriel Gore"
author-email = "gabriel59kg@gmail.com"
home-page = "https://github.com/Kilo59/blue-chip"
requires = [
    "black",
    "invoke",
    "prospector[with_pyroma]",]
requires-python = ">=3.6"

[tool.flit.scripts]
bc = "blue_chip.__main__:program.run"
