[tool.poetry]
name = "blue-chip"
version = "0.1.0"
description = "One click Python code quality suite"
authors = ["Gabriel <gabriel59kg@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
black = "stable"
invoke = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
