jobs: 
- job: Build_Linux 
  pool:  
   vmImage: 'ubuntu-16.04'
  steps: 
    - template: templates/steps.yml
- job: Build_Windows  
  pool:  
   vmImage: 'vs2017-win2016'
  steps: 
    - template: templates/steps.yml
